import { BarcodeProvider } from "@/contexts/BarcodeContext";
import "@/styles/globals.css";

export const metadata = {
  title: "Barcode",
  description: "Generated by Next.js",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" data-theme="dim">
      <body>
        <BarcodeProvider>{children}</BarcodeProvider>
      </body>
    </html>
  );
}
